Unpin pylint (#1277)
* Unpin pylint

* Avoid using non-existant variable

* Remove useless pylint control

* Fix warning string

* Replace range calculation with quadratic calculation

* Actually raise exceptions if failures occur

* Replace badly chained expression

* Formatting with black

* Lower pylint standards slightly

* Use bash exit codes to determine pylint status

diff --git a/.github/workflows/subsurface.yml b/.github/workflows/subsurface.yml
--- a/.github/workflows/subsurface.yml
+++ b/.github/workflows/subsurface.yml
@@ -72,7 +72,18 @@ jobs:
         if: github.event_name != 'release'
         run: |
           black --check webviz_subsurface tests setup.py
-          pylint webviz_subsurface tests setup.py
+
+          pylint_exit_code=0
+          pylint webviz_subsurface tests setup.py || pylint_exit_code=$?
+
+          error_bitmask=$((1 | 2 | 4))  # Fatal, Error, Warning
+          result=$(($pylint_exit_code & $error_bitmask))
+
+          if [[ $result != 0 ]]; then
+            echo "Error: Pylint returned exit code $pylint_exit_code"
+            exit $pylint_exit_code
+          fi
+
           bandit -r -c ./bandit.yml webviz_subsurface tests setup.py
           isort --check-only webviz_subsurface tests setup.py
           mypy --package webviz_subsurface
